### ISSUE TITLE
ssh-brute.nse

### ISSUE THREAD

**Issue by nimicent** [andreas-marschke/misc-tools#1]
Hey Andreas,

I tried to use the ssh-brute.nse, dropped it in my /usr/share/nmap/scripts/ folder, chmod 777, then did this command following your great documentation on using this:

Have any idea about this? Do I actually need to put the host key in here? Because on the output, it looks like this identifies the SSH host key along with enumerating users (doing OSCP). 

Thanks for any feedback. I did then try to put the SSH host key in place for possible placeholder of SSH-hostkey in your example script, and received this same error:

```
nmap 10.0.0.0 --script SSH-hostkey --script-args ssh_hostkey=all

Starting Nmap 7.40 ( https://nmap.org ) at 2017-06-12 17:51 CDT
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:816: 'SSH-hostkey' did not match a category, filename, or directory
stack traceback:
	[C]: in function 'error'
	/usr/bin/../share/nmap/nse_main.lua:816: in local 'get_chosen_scripts'
	/usr/bin/../share/nmap/nse_main.lua:1271: in main chunk
	[C]: in ?

QUITTING!
```

**Comment by andreas-marschke** [comment]
I never finished this I don't think it ever really worked. Sorry if it was misleading.
